### ISSUE TITLE
Works with outliner plugin

### ISSUE THREAD

**Issue by Quorafind** [mgmeyers/obsidian-indentation-guides#1]
![image](https://user-images.githubusercontent.com/13215013/147619153-59ae3e79-7046-4831-abed-69614c3fcd99.png)

**Comment by mgmeyers** [comment]
@Quorafind Could you send me the markdown you're using here? Also, are you using the default theme, or something else?

**Comment by Quorafind** [comment]
Yes , I am using default theme to test the plugin.

here is the markdown code:

```
- <time>09:11</time> BTC:USD price = 57,669.85
- <time>12:51</time> [McMaster-Carr](https://www.mcmaster.com/)
    - Fast, snappy, responsive. No banners or cookie prompts, doesn't ask my to sign up for a newsletter or an account to continue and see more selection, it doesn't load in megabytes of JavaScript to show me products.
    - 
```

**Comment by Quorafind** [comment]
Okay, I do know why, 
![image](https://user-images.githubusercontent.com/13215013/147620434-3e4d143b-fbb7-4142-b7f0-dd7eaee9eca6.png)

Though I closed this option in outliner, it seems wrote something about bullet line in the default style css.

**Comment by Quorafind** [comment]
Now the question should change to how to make outliner works with indention guides. 🧐

**Comment by mgmeyers** [comment]
Thanks @Quorafind, I've made some changes so this plugin will now override the styles of the outliner plugin. Let me know if you have any issues with it.
