### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by imeed166** [mgmeyers/obsidian-indentation-guides#2]
Hi, thank you for this plugin. Can you add a setting to change the color of the indentation lines and the color when hovering ?

**Comment by mgmeyers** [comment]
Thanks @imeed166, I've added some style settings to control the colors of the lines. You'll have to install the Style Settings plugin to access them:

<img width="783" alt="Screen Shot 2022-01-03 at 4 53 20 PM" src="https://user-images.githubusercontent.com/2694747/147995717-63df3258-b680-4f9f-8b54-84fcfec59d90.png">

Let me know if this works for you.

**Comment by imeed166** [comment]
Yes, works great, thank you.
