### ISSUE TITLE
Adjust position of the lines

### ISSUE THREAD

**Issue by imeed166** [mgmeyers/obsidian-indentation-guides#3]
I'm using the shimmering focus theme and the indentation line is slightly to the left compared to the default theme. I don't know if this is out of scope of this plugin or if I should make an issue in the theme repo. 
But can you add on option to adjust this in the style settings so that the plugin can be made compatible with any theme ?

![image](https://user-images.githubusercontent.com/38974541/148027022-4d758732-5fb4-434d-88d8-2dd204c1dc80.png)

![image](https://user-images.githubusercontent.com/38974541/148027053-1d0dc96b-7898-44d4-b58a-82c3265e22a5.png)

**Comment by mgmeyers** [comment]
Thanks for the idea @imeed166. I've added a style setting to adjust the position. Let me know if you have any issues with it.

**Comment by imeed166** [comment]
Yep, it's perfect, thank you.
