### ISSUE TITLE
Add indentation lines to reading view mode

### ISSUE THREAD

**Issue by imeed166** [mgmeyers/obsidian-indentation-guides#4]
There should be a line between task1 and task2

![image](https://user-images.githubusercontent.com/38974541/148037153-e0b15802-1f0c-418a-ab9c-31c4f5db789b.png)

I have enabled everything in the settings.

![image](https://user-images.githubusercontent.com/38974541/148037191-321b660b-8a06-4afe-907d-4aab312e1934.png)

Here are the files if you need them.
[test.zip](https://github.com/mgmeyers/obsidian-indentation-guides/files/7806594/test.zip)

**Comment by imeed166** [comment]
I found that it's not related to the task query, it just doesn't add relationship lines in reading view mode.

**Comment by mgmeyers** [comment]
Thanks @imeed166, this has been added. Let me know if you have any issues with it.

**Comment by imeed166** [comment]
It works as intended, I just needed to adjust the position a bit, and it was easily done via the new style setting, thank you.
